name: reformat
on: [push]
jobs:
  reformat:
    name: reformat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: install-requirements
        continue-on-error: true
        run: |
          python -m pip install black isort
      - name: black-isort
        continue-on-error: true
        run: |
          python -m black . -l 80
          python -m isort -l 80 --profile black .
      - name: commit-changes
        continue-on-error: true
        run: |
          git config --local committer.email "noreply@github.com"
          git config --local committer.name "GitHub"
          git config --local author.email "${{ github.actor }}@users.noreply.github.com"
          git config --local author.name "{{ github.actor }}"
          git add -A
          git commit -m "black + isort"
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:${GITHUB_REF#refs/heads/}
